### ISSUE TITLE
Tyte-cli runs the another command instead of the specified command

### ISSUE THREAD

**Issue by yaaminu** [tytejs/tyte-cli#1]
There seems to be a bug where tyte-cli runs an arbitrary command ignoring the actual command specified on the command line. 

example 
`node dist/Index.js abc` should only run the command registered with name the "abc"  but the bug causes another command registered with a different name to be ran.

**Comment by Norris1z** [comment]
Can you post some steps to replicate the bug? I just tried creating two commands and it works as expected.

**Comment by yaaminu** [comment]
Well I have no idea. The bug was triggered after I made some changes to the api in attempt to simplify it. I'll be pushing a fix soon

**Comment by Norris1z** [comment]
Cool. I think we need to create a dev branch so all our code there before merging major fixes to master. I hope you're pushing a fix for the `.tsconfig` too.

**Comment by yaaminu** [comment]
Sure, all my changes goes to `dev`. Kindly do check that out and make sure you never push directly to `master`

**Comment by Norris1z** [comment]
I think you should consider rewriting the example in the readme now that you've simplified the api

**Comment by yaaminu** [comment]
I'll open a new issue for that
