### ISSUE TITLE
Allow users to specify the configurations for the Application

### ISSUE THREAD

**Issue by Norris1z** [tytejs/tyte-cli#4]
The `Application.ts` class should have methods for getting and setting some basic config such as the application `name,version,description` etc

**Comment by yaaminu** [comment]
@Norris1z You'd want to pull the recent changes and play around a bit, I've made some changes that you need to know. Btw why do you think this's neccessary now?

**Comment by Norris1z** [comment]
At its current state, you can create an application with your specified commands. I think it'll make sense if you can configure your application before adding your commands.
Btw it has default values so it'll still work either ways.
